[build]
publish = "public"
command = "npm install && npm run build"

[build.environment]
HUGO_VERSION = "0.149.0"
GO_VERSION = "1.24.2"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build.processing]
skip_processing = false
